### ISSUE TITLE
[BUG] Jacobian computation incorrect for prismatic joints

### ISSUE THREAD

**Issue by LemonPi** [nnadeau/pybotics#764]
## Description

Prismatic joints are ignored in the Jacobian computation. Note that this was discovered through the same problem in [kinpy issue](https://github.com/neka-nat/kinpy/issues/5), which uses very similar code.

## Steps to Reproduce

1. Create a robot with purely prismatic joints, such as defined by this URDF file:
```
<robot name="prismatic_robot"> 
<link name="link1" />
<link name="link2" />
<link name="link3" />
<link name="link4" />

<joint name="joint1" type="prismatic">
    <origin xyz="0.0 0.0 1.0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="1" velocity="1"/>
    <parent link="link1"/>
    <child link="link2"/>
</joint>
<joint name="joint2" type="prismatic">
    <origin xyz="0.0 0.0 0.0" rpy="1.57079632679 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="1" velocity="1"/>
    <parent link="link2"/>
    <child link="link3"/>
</joint>
<joint name="joint3" type="prismatic">
    <origin xyz="0.0 0.0 0.0" rpy="0 1.57079632679 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-0.5" upper="0.5" effort="1" velocity="1"/>
    <parent link="link3"/>
    <child link="link4"/>
</joint>

</robot>
```
2. Compute Jacobian in world/base frame with any configuration
3. Produce the zero matrix as the Jacobian

## Expected Behavior

The Jacobian of this robot for any configuration should be
```
                                           [[0., 0., 1.],
                                            [0., -1., 0.],
                                            [1., 0., 0.],
                                            [0., 0., 0.],
                                            [0., 0., 0.],
                                            [0., 0., 0.]]
```

## Additional Context

I did not directly run pybotics code, but discovered this problem through kinpy, which uses the same code to compute Jacobians. There, the robots can be defined via URDF files, hence I provided the URDF here.
I discovered this problem while building my [pytorch kinematics](https://github.com/UM-ARM-Lab/pytorch_kinematics/) project, with a solution [in this file](https://github.com/UM-ARM-Lab/pytorch_kinematics/blob/master/pytorch_kinematics/jacobian.py). However, I am not familiar with the pybotics code base so am not sure how to directly port that over.

**Comment by nnadeau** [comment]
hi @LemonPi 

Prismatic links need to use the `PrismaticMDHLink` class (see below). Since they're used much less regularly than revolute joints (in my research and work at least), I never made many helper functions for these. I'd be happy if you wanted to contribute prismatic code features, that would help a lot!

https://github.com/nnadeau/pybotics/blob/90e3503417300fc63b2f224a416c1f95369dc9b3/pybotics/link.py#L156-L161

Otherwise, I'm not familiar with `kinpy` nor do I know of any code connection.

Closing this ticket as prismatic joints are relatively supported, but it's also more of a feature request if you're looking for a direct URDF -> `pybotics` feature
